hik_camera:
  ros__parameters:
    camera_sn: "00L34964883"        # ✅ 使用序列号
    exposure_time: 5000.0          # 10ms，适合室内
    gain: 3.0                       # 适度增益
    frame_rate: -1.0                # 最大帧率
    pixel_format: "BGR8"            